(()=>{'use strict';
const C=window.LightLineCatalog,D=new TextDecoder('utf-8'),E=new TextEncoder(),S={tab:'skills',q:'',sel:new Set(),active:null};
const R={
'new-frontend-feature':['frontend-stack-mistake-book','frontend-component-mistake-book','frontend-ui-mistake-book','repo-delivery-governance'],
'refactor-window-module':['window-module-boundary','shared-component-governance','database-window-governance','macro-window-governance','window4-chat-governance'],
'connect-bff-rag':['bff-route-governance','fastapi-mia-rag-integration','federation-chat-integration','window4-chat-governance'],
'optimize-motion-timeline':['frontend-motion-mistake-book','frontend-timeline-mistake-book','trace-graph-physics-optimization','chat-initial-state-optimization'],
'delivery-review':['repo-delivery-governance','noob-deployment-tutorial','frontend-stack-mistake-book','window-module-boundary']};
const HR={'session-start.mjs':['repo-delivery-governance','window-module-boundary'],'user-prompt-submit.mjs':['new-frontend-feature','refactor-window-module','connect-bff-rag','optimize-motion-timeline','delivery-review'],'pre-tool-use.mjs':['repo-delivery-governance','window-module-boundary'],'post-tool-use.mjs':['delivery-review','repo-delivery-governance','frontend-motion-mistake-book']};
const W={'new-frontend-feature':'workflows/新增前端功能.md','refactor-window-module':'workflows/改造窗口模块.md','connect-bff-rag':'workflows/接入BFF-RAG.md','optimize-motion-timeline':'workflows/优化动效时间轴.md','delivery-review':'workflows/交付前审查.md'};
const el={list:gid('selection-list'),search:gid('search-input'),preview:gid('preview-card'),total:gid('selected-total'),size:gid('package-size'),gcount:gid('graph-count'),graph:gid('logic-graph'),full:gid('download-full'),custom:gid('download-custom')};
const ALL=[...C.skills,...C.commands,...C.hooks];ALL.forEach(x=>S.sel.add(x.id));S.active=C.skills[0]?.id||null;
function gid(id){return document.getElementById(id)}
function items(t){return t==='skills'?C.skills:t==='commands'?C.commands:C.hooks}
function chosen(t){return items(t).filter(x=>S.sel.has(x.id))}
function bytes(f){const b=atob(f.contentBase64),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return u}
function text(f){return D.decode(bytes(f))}
function esc(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function short(v,n){return v.length>n?v.slice(0,n-1)+'...':v}
function renderList(){const q=S.q.trim().toLowerCase(),arr=items(S.tab).filter(x=>!q||[x.title,x.id,x.category,x.description].join(' ').toLowerCase().includes(q));el.list.innerHTML='';if(!arr.length){el.list.innerHTML='<div class="item-row"><div></div><div><strong>没有匹配项</strong><p>换一个关键词，或者切换 Skills / Commands / Hooks。</p></div></div>';return}arr.forEach(x=>{const lab=document.createElement('label');lab.className='item-row';lab.innerHTML=`<input type="checkbox" ${S.sel.has(x.id)?'checked':''} aria-label="选择 ${esc(x.title)}"><span><strong>${esc(x.title)}</strong><small>${esc(x.id)}</small><p><span class="category-stamp">${esc(x.category)}</span>${esc(x.description)}</p></span>`;lab.addEventListener('click',e=>{if(e.target.tagName!=='INPUT'){S.active=x.id;renderPreview()}});lab.querySelector('input').addEventListener('change',e=>{e.target.checked?S.sel.add(x.id):S.sel.delete(x.id);S.active=x.id;renderAll()});el.list.appendChild(lab)})}
function renderPreview(){const x=ALL.find(i=>i.id===S.active)||ALL[0];if(!x)return;const f=C.files.find(i=>i.path===x.primaryPath),body=f?text(f):x.description,ex=body.split(/\r?\n/).slice(0,18).join('\n').trim();el.preview.innerHTML=`<div class="meta-line"><span>${esc(x.type)}</span><span>${esc(x.category)}</span><span>${S.sel.has(x.id)?'已纳入当前包':'当前未选择'}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><pre>${esc(ex||'该条目暂无可预览正文。')}</pre>`}
function pathSet(mode){if(mode==='full')return new Set(C.files.map(f=>f.path));const p=new Set(['.codex-plugin/plugin.json','README.md','技能索引.md']);chosen('skills').forEach(s=>C.files.forEach(f=>{if(f.path.startsWith(`skills/${s.id}/`))p.add(f.path)}));const cmds=chosen('commands');if(cmds.length)p.add('commands/README.md');cmds.forEach(c=>{p.add(c.primaryPath);if(W[c.id])p.add(W[c.id])});const hs=chosen('hooks');if(hs.length){p.add('hooks/README.md');p.add('hooks/hooks.json')}hs.forEach(h=>p.add(h.primaryPath));return p}
function selMd(){const row=a=>a.map(x=>`- ${x.title} (${x.id})`).join('\n')||'- 未选择';return `# Light_line 自定义选择清单\n\n生成时间：${new Date().toISOString()}\n\n## Skills\n${row(chosen('skills'))}\n\n## Commands\n${row(chosen('commands'))}\n\n## Hooks\n${row(chosen('hooks'))}\n\n## 运行边界\n- hooks 需要 Codex 插件启用、用户信任并具备 Node 运行环境。\n- commands 是 pm-skills 式流程模板，不是 Codex 当前自动注册的 slash command。\n`}
function pack(mode){const ps=pathSet(mode),out=C.files.filter(f=>ps.has(f.path)).map(f=>({path:'light-line/'+f.path,bytes:bytes(f)}));if(mode!=='full')out.push({path:'light-line/LIGHT_LINE_SELECTION.md',bytes:E.encode(selMd())});return out}
function counters(){el.total.textContent=S.sel.size+' selected';el.size.textContent=(pathSet('custom').size+1)+' files';gid('skill-count').textContent=C.skills.length;gid('command-count').textContent=C.commands.length;gid('hook-count').textContent=C.hooks.length}
function svg(t,a={}){const n=document.createElementNS('http://www.w3.org/2000/svg',t);Object.entries(a).forEach(([k,v])=>n.setAttribute(k,v));return n}
function node(n){const g=svg('g',{class:'graph-node '+n.type,tabindex:'0'});g.append(svg('rect',{x:n.x,y:n.y,width:n.w,height:n.h}));let a=svg('text',{x:n.x+9,y:n.y+13,class:'node-type'});a.textContent=n.type;let b=svg('text',{x:n.x+9,y:n.y+(n.h>40?35:22)});b.textContent=short(n.title,n.w>200?31:18);g.append(a,b);return g}
function renderGraph(){const g=el.graph;[...g.querySelectorAll('defs,path.graph-edge,g.graph-node')].forEach(n=>n.remove());const defs=svg('defs'),m=svg('marker',{id:'arrow',markerWidth:'8',markerHeight:'8',refX:'7',refY:'3',orient:'auto',markerUnits:'strokeWidth'});m.append(svg('path',{d:'M0,0 L0,6 L8,3 z',fill:'#111111'}));defs.append(m);g.append(defs);const ns=[{id:'manifest',title:'plugin.json',type:'core',x:28,y:295,w:132,h:56}];chosen('hooks').forEach((x,i)=>ns.push({id:x.id,title:x.title,type:'hook',x:210,y:42+i*86,w:156,h:58}));chosen('commands').forEach((x,i)=>ns.push({id:x.id,title:x.title,type:'command',x:430,y:72+i*108,w:172,h:62}));chosen('skills').forEach((x,i)=>ns.push({id:x.id,title:x.title,type:'skill',x:670,y:18+i*36,w:270,h:30}));ns.push({id:'zip',title:'ZIP 插件包',type:'core',x:790,y:640,w:150,h:44});const M=new Map(ns.map(n=>[n.id,n])),es=[];[...chosen('hooks'),...chosen('commands'),...chosen('skills')].forEach(x=>es.push(['manifest',x.id,'normal']));chosen('hooks').forEach(h=>(HR[h.id]||[]).forEach(t=>{if(S.sel.has(t))es.push([h.id,t,'guard'])}));chosen('commands').forEach(c=>(R[c.id]||[]).forEach(t=>{if(S.sel.has(t))es.push([c.id,t,'normal'])}));[...chosen('skills'),...chosen('commands')].forEach(x=>es.push([x.id,'zip','normal']));chosen('hooks').forEach(x=>es.push([x.id,'zip','guard']));[...new Map(es.map(e=>[e.join('-'),e])).values()].forEach(([a,b,k])=>{const A=M.get(a),B=M.get(b);if(!A||!B)return;const sx=A.x+A.w,sy=A.y+A.h/2,ex=B.x,ey=B.y+B.h/2,mx=sx+Math.max(38,(ex-sx)/2);g.append(svg('path',{class:'graph-edge '+k,d:`M${sx},${sy} C${mx},${sy} ${mx},${ey} ${ex},${ey}`}))});ns.forEach(n=>g.append(node(n)));el.gcount.textContent=ns.length+' nodes'}
function zip(files){const chunks=[],central=[];let off=0;files.sort((a,b)=>a.path.localeCompare(b.path,'zh-CN'));for(const f of files){const name=E.encode(f.path.replace(/\\/g,'/')),data=f.bytes,crc=crc32(data),loc=new Uint8Array(30+name.length);w32(loc,0,0x04034b50);w16(loc,4,20);w32(loc,14,crc);w32(loc,18,data.length);w32(loc,22,data.length);w16(loc,26,name.length);loc.set(name,30);chunks.push(loc,data);const rec=new Uint8Array(46+name.length);w32(rec,0,0x02014b50);w16(rec,4,20);w16(rec,6,20);w32(rec,16,crc);w32(rec,20,data.length);w32(rec,24,data.length);w16(rec,28,name.length);w32(rec,42,off);rec.set(name,46);central.push(rec);off+=loc.length+data.length}const size=central.reduce((s,c)=>s+c.length,0),end=new Uint8Array(22);w32(end,0,0x06054b50);w16(end,8,files.length);w16(end,10,files.length);w32(end,12,size);w32(end,16,off);return new Blob([...chunks,...central,end],{type:'application/zip'})}
function w16(b,o,v){b[o]=v&255;b[o+1]=v>>>8&255}function w32(b,o,v){b[o]=v&255;b[o+1]=v>>>8&255;b[o+2]=v>>>16&255;b[o+3]=v>>>24&255}
const T=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^c>>>1:c>>>1;t[n]=c>>>0}return t})();function crc32(bs){let c=0xffffffff;for(let i=0;i<bs.length;i++)c=T[(c^bs[i])&255]^c>>>8;return(c^0xffffffff)>>>0}
function dl(mode){const url=URL.createObjectURL(zip(pack(mode))),a=document.createElement('a');a.href=url;a.download=mode==='full'?'light-line-plugin-full.zip':'light-line-plugin-custom.zip';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function renderAll(){counters();renderList();renderPreview();renderGraph()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===b));S.active=items(S.tab)[0]?.id||S.active;renderAll()});
document.querySelector('[data-action="select-all"]').onclick=()=>{ALL.forEach(x=>S.sel.add(x.id));renderAll()};document.querySelector('[data-action="clear-all"]').onclick=()=>{S.sel.clear();renderAll()};document.querySelector('[data-action="invert-all"]').onclick=()=>{ALL.forEach(x=>S.sel.has(x.id)?S.sel.delete(x.id):S.sel.add(x.id));renderAll()};el.search.oninput=e=>{S.q=e.target.value;renderList()};el.full.onclick=()=>dl('full');el.custom.onclick=()=>dl('custom');renderAll();
})();